# Generated by Django 4.2.17 on 2024-12-09 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.IntegerField(db_column='EmployeeID')),
                ('EmployeeName', models.CharField(db_column='EmployeeName', max_length=50)),
                ('List_Tasks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhaseID', models.IntegerField(db_column='PhaseID')),
                ('PhaseName', models.CharField(db_column='PhaseName', max_length=50)),
                ('Pourcentage', models.IntegerField(db_column='Pourcentage')),
            ],
            options={
                'db_table': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField(db_column='TaskID')),
                ('Responsible', models.CharField(db_column='Responsible', max_length=100)),
                ('TaskDaysAllowed', models.IntegerField(db_column='TaskDaysAllowed', default=0)),
                ('TaskDaysWorked', models.IntegerField(db_column='TaskDaysWorked', default=0)),
                ('TaskDesc', models.CharField(db_column='TaskDesc', max_length=50)),
                ('StartingDay', models.IntegerField()),
                ('State', models.CharField(db_column='State', default='Assigned To', max_length=50)),
            ],
        ),
    ]
