# Generated by Django 4.2.17 on 2024-12-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('pages', '0004_rename_customuser_auth_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user',
            new_name='CustomUser',
        ),
    ]
