# Generated by Django 4.2.17 on 2024-12-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
