# Generated by Django 4.2.17 on 2025-01-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Bill_ID',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
