# Generated by Django 4.2.17 on 2025-01-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_invoice_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Bill_ID',
            field=models.CharField(db_column='Bill_ID', max_length=255),
        ),
    ]
