# Generated by Django 4.2.17 on 2025-01-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
    ]
